import { makeStyles } from '@material-ui/core/styles';

export default makeStyles((theme) => ({
	item: {
		display: 'inline-block',
		position: 'relative',
		paddingBottom: '56.25%',
		width: '100%',
		cursor: 'pointer',
		backgroundPosition: 'center',
		backgroundRepeat: 'no-repeat',
		backgroundSize: 'cover',
		overflow: 'hidden',
		'&:hover $itemMenu': {
			transform: 'translateY(0)',
		},
	},
	itemMenu: {
		cursor: 'default',
		position: 'absolute',
		left: 0,
		top: '70%',
		bottom: '0',
		width: '100%',
		backgroundColor: 'rgba(0, 0, 0, 0.75)',
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		transform: 'translateY(101%)',
		transition: theme.transitions.create('transform', {
			easing: theme.transitions.easing.easeOut,
			duration: theme.transitions.duration.short,
		}),
	},
	itemMenuButton: {
		margin: theme.spacing(0, 0.5),
	},
	workButton: {
		backgroundColor: theme.palette.warning.main,
		color: '#fff',
	},
	nsfwButton: {
		display: 'flex',
		position: 'absolute',
		top: theme.spacing(2),
		right: theme.spacing(6),
		zIndex: 10,
		cursor: 'pointer',
		userSelect: 'none',
		borderRadius: 100,
		backgroundColor: theme.palette.secondary.main,
		color: '#fff',
		width: theme.spacing(3),
		height: theme.spacing(3),
		alignItems: 'center',
		justifyContent: 'center',
		fontWeight: 600,
	},
	infoButton: {
		display: 'flex',
		position: 'absolute',
		top: theme.spacing(2),
		right: theme.spacing(2),
		zIndex: 10,
		cursor: 'pointer',
		userSelect: 'none',
		borderRadius: 100,
		backgroundColor: theme.palette.primary.main,
		color: '#fff',
		width: theme.spacing(3),
		height: theme.spacing(3),
		alignItems: 'center',
		justifyContent: 'center',
		fontWeight: 600,
		paddingTop: 2,
		boxSizing: 'border-box',
	},
}));
